package vase

// This file is generated from node/avatar-grid.js so the Go port keeps the same
// palette and 9x17 template vocabulary as the Node renderer.

type Template []string

var colors = []Color{
	{Name: "deep moss", Code: 22, RGB: [3]float64{0, 95, 0}, Tone: "dark", Family: "green", Weight: 0.35},
	{Name: "ivy green", Code: 28, RGB: [3]float64{0, 135, 0}, Tone: "dark", Family: "green", Weight: 0.3},
	{Name: "mulch olive", Code: 58, RGB: [3]float64{95, 95, 0}, Tone: "dark", Family: "green", Weight: 0.45},
	{Name: "leaf shadow", Code: 64, RGB: [3]float64{95, 135, 0}, Tone: "dark", Family: "green", Weight: 0.35},
	{Name: "black violet", Code: 53, RGB: [3]float64{95, 0, 95}, Tone: "dark", Family: "purple", Weight: 1.25},
	{Name: "wild plum", Code: 54, RGB: [3]float64{95, 0, 135}, Tone: "dark", Family: "purple", Weight: 1.2},
	{Name: "iris purple", Code: 90, RGB: [3]float64{135, 0, 135}, Tone: "dark", Family: "purple", Weight: 1.15},
	{Name: "crocus", Code: 91, RGB: [3]float64{135, 0, 175}, Tone: "dark", Family: "purple", Weight: 1.05},
	{Name: "nightshade", Code: 17, RGB: [3]float64{0, 0, 95}, Tone: "dark", Family: "blue", Weight: 0.75},
	{Name: "gentian", Code: 18, RGB: [3]float64{0, 0, 135}, Tone: "dark", Family: "blue", Weight: 0.7},
	{Name: "delphinium", Code: 19, RGB: [3]float64{0, 0, 175}, Tone: "dark", Family: "blue", Weight: 0.65},
	{Name: "ink iris", Code: 55, RGB: [3]float64{95, 0, 175}, Tone: "dark", Family: "indigo", Weight: 0.9},
	{Name: "violet night", Code: 57, RGB: [3]float64{95, 0, 255}, Tone: "dark", Family: "indigo", Weight: 0.72},
	{Name: "bluebell shadow", Code: 60, RGB: [3]float64{95, 95, 135}, Tone: "dark", Family: "indigo", Weight: 0.62},
	{Name: "black cherry", Code: 52, RGB: [3]float64{95, 0, 0}, Tone: "dark", Family: "red", Weight: 1.45},
	{Name: "burgundy", Code: 88, RGB: [3]float64{135, 0, 0}, Tone: "dark", Family: "red", Weight: 1.35},
	{Name: "rosewood", Code: 89, RGB: [3]float64{135, 0, 95}, Tone: "dark", Family: "pink", Weight: 1.35},
	{Name: "wineberry", Code: 125, RGB: [3]float64{175, 0, 95}, Tone: "dark", Family: "pink", Weight: 1.15},
	{Name: "new leaf", Code: 118, RGB: [3]float64{135, 255, 0}, Tone: "light", Family: "green", Weight: 0.28},
	{Name: "chartreuse", Code: 154, RGB: [3]float64{175, 255, 0}, Tone: "light", Family: "green", Weight: 0.35},
	{Name: "pollen", Code: 190, RGB: [3]float64{215, 255, 0}, Tone: "light", Family: "yellow", Weight: 0.75},
	{Name: "marigold", Code: 220, RGB: [3]float64{255, 215, 0}, Tone: "light", Family: "yellow", Weight: 0.85},
	{Name: "sunflower", Code: 226, RGB: [3]float64{255, 255, 0}, Tone: "light", Family: "yellow", Weight: 0.75},
	{Name: "lilac", Code: 183, RGB: [3]float64{215, 175, 255}, Tone: "light", Family: "purple", Weight: 1.1},
	{Name: "periwinkle", Code: 147, RGB: [3]float64{175, 175, 255}, Tone: "light", Family: "indigo", Weight: 0.9},
	{Name: "hydrangea", Code: 153, RGB: [3]float64{175, 215, 255}, Tone: "light", Family: "blue", Weight: 0.82},
	{Name: "blue flax", Code: 159, RGB: [3]float64{215, 255, 255}, Tone: "light", Family: "blue", Weight: 0.65},
	{Name: "pale iris", Code: 189, RGB: [3]float64{215, 215, 255}, Tone: "light", Family: "indigo", Weight: 0.82},
	{Name: "forget me not", Code: 111, RGB: [3]float64{135, 175, 255}, Tone: "light", Family: "blue", Weight: 0.72},
	{Name: "phlox", Code: 219, RGB: [3]float64{255, 175, 255}, Tone: "light", Family: "pink", Weight: 1.3},
	{Name: "pink alyssum", Code: 224, RGB: [3]float64{255, 215, 215}, Tone: "light", Family: "pink", Weight: 1.35},
	{Name: "peony", Code: 217, RGB: [3]float64{255, 175, 215}, Tone: "light", Family: "pink", Weight: 1.45},
	{Name: "rose", Code: 211, RGB: [3]float64{255, 135, 175}, Tone: "light", Family: "pink", Weight: 1.25},
	{Name: "salmon", Code: 210, RGB: [3]float64{255, 135, 135}, Tone: "light", Family: "red", Weight: 1.05},
	{Name: "fuchsia", Code: 201, RGB: [3]float64{255, 0, 255}, Tone: "light", Family: "pink", Weight: 0.9},
}

var backgrounds = []Template{
	{
		"█░█░█░█░█░█░█░█░█",
		"░█░█░█░█░█░█░█░█░",
		"█░█░█░█░█░█░█░█░█",
		"░█░█░█░█░█░█░█░█░",
		"█░█░█░█░█░█░█░█░█",
		"░█░█░█░█░█░█░█░█░",
		"█░█░█░█░█░█░█░█░█",
		"░█░█░█░█░█░█░█░█░",
		"█░█░█░█░█░█░█░█░█",
	},
	{
		"      ░█░█░█░",
		"   ░█░█░█░█░█░█░",
		" █░█░█░█░█░█░█░█░█",
		" ░█░█░█░█░█░█░█░█░",
		" █░█░█░█░█░█░█░█░█",
		" ░█░█░█░█░█░█░█░█░",
		" █░█░█░█░█░█░█░█░█",
		"   ░█░█░█░█░█░█░",
		"      ░█░█░█░",
	},
	{
		"█░█░█░█░█░█░█░█░█",
		"   ░█░█░█░█░█░█░",
		"     █░█░█░█░█",
		"        █░█",
		"         █",
		"        █░█",
		"     █░█░█░█░█",
		"   ░█░█░█░█░█░█░",
		"█░█░█░█░█░█░█░█░█",
	},
	{
		"     █░█░█░█░█",
		"     ░█░█░█░█░",
		"    ░█░█░█░█░█░",
		"    █░█░█░█░█░█",
		"   █░█░█░█░█░█░█",
		"   ░█░█░█░█░█░█░",
		"  ░█░█░█░█░█░█░█░",
		"  █░█░█░█░█░█░█░█",
		"█░█░█░█░█░█░█░█░█",
	},
	{
		"█░█░█░█░█░█░█░█░█",
		"   ░█░█░█░█░█░█░",
		"     █░█░█░█░█",
		"   ░█░█░█░█░█░█░",
		"█░█░█░█░█░█░█░█░█",
		"   ░█░█░█░█░█░█░",
		"     █░█░█░█░█",
		"   ░█░█░█░█░█░█░",
		"█░█░█░█░█░█░█░█░█",
	},
	{
		"█░█           █░█",
		"░█             █░",
		"█               █",
		"",
		"",
		"",
		"█               █",
		"░█             █░",
		"█░█           █░█",
	},
	{
		"   █     █     █",
		"  █░█   █░█   █░█",
		"█░█░█░█░█░█░█░█░█",
		"   █     █     █",
		"  █░█   █░█   █░█",
		"█░█░█░█░█░█░█░█░█",
		"   █     █     █",
		"  █░█   █░█   █░█",
		"█░█░█░█░█░█░█░█░█",
	},
	{
		"   █   █   █   █",
		"  █░█   █░█   █░█",
		"█░ ░█  ░█░  █░ ░█",
		"   █   █   █   █",
		"  █░█   █░█   █░█",
		"█░ ░█  ░█░  █░ ░█",
		"   █   █   █   █",
		"  █░█   █░█   █░█",
		"█░ ░█  ░█░  █░ ░█",
	},
	{
		"      ░█░█░█░",
		"   ░█░█░█░█░█░█░",
		"  ░█░█░█░█░█░█░█░",
		"░█░█░█░█░█░█░█░█░",
		"",
		"",
		"",
		"   ░█░█░█░█░█░█░",
		"      ░█░█░█░",
	},
	{
		"",
		"",
		"",
		"",
		"",
		"░█░█░█░█░█░█░█░█░",
		"  ░█░█░█░█░█░█░█░",
		"   ░█░█░█░█░█░█░",
		"      ░█░█░█░",
	},
	{
		"   ╭─╭─╭───╮─╮─╮",
		"  ╭╯╭╯╭╯╭─╮╰╮╰╮╰╮",
		" ╭╯╭╯╭╯╭╯ ╰╮╰╮╰╮╰╮",
		" │ │ │ │╭─╮│ │ │ │",
		" │ │ │ ││ ││ │ │ │",
		" │ │ │ │╰─╯│ │ │ │",
		" ╰╮╰╮╰╮╰╮ ╭╯╭╯╭╯╭╯",
		"  ╰╮╰╮╰╮╰─╯╭╯╭╯╭╯",
		"   ╰─╰─╰───╯─╯─╯",
	},
	{
		"╭╮╭╮╭╮╭╭─╮╮╭╮╭╮╭╮",
		"│╭╯╭╯╭╯╭─╮╰╮╰╮╰╮│",
		"╭╯╭╯╭╯╭╯┬╰╮╰╮╰╮╰╮",
		"│││││││╭┴╮│││││││",
		"││││││││ ││││││││",
		"│││││││╰┬╯│││││││",
		"╰╮╰╮╰╮╰╮┴╭╯╭╯╭╯╭╯",
		"│╰╮╰╮╰╮╰─╯╭╯╭╯╭╯│",
		"╰╯╰╯╰╯╰╰─╯╯╰╯╰╯╰╯",
	},
	{
		"╭╭╭╭╭╭╭╭─╮╮╮╮╮╮╮╮",
		"╭╭╭╭╭╭╭╭─╮╮╮╮╮╮╮╮",
		"╭╭╭╭╭╭╭╭─╮╮╮╮╮╮╮╮",
		"╭╭╭╭╭╭╭╭─╮╮╮╮╮╮╮╮",
		"││││││││ ││││││││",
		"╰╰╰╰╰╰╰╰─╯╯╯╯╯╯╯╯",
		"╰╰╰╰╰╰╰╰─╯╯╯╯╯╯╯╯",
		"╰╰╰╰╰╰╰╰─╯╯╯╯╯╯╯╯",
		"╰╰╰╰╰╰╰╰─╯╯╯╯╯╯╯╯",
	},
	{
		"────────────────╮",
		"╭──────────────╮│",
		"│╭────────────╮││",
		"││╭──────────╮│││",
		"│││╭──────── ││││",
		"│││╰─────────╯│││",
		"││╰───────────╯││",
		"│╰─────────────╯│",
		"╰───────────────╯",
	},
	{
		"╭╮             ╭╮",
		"╰┼─────────────┼╯",
		" │             │",
		" │             │",
		" │             │",
		" │             │",
		" │             │",
		"╭┼─────────────┼╮",
		"╰╯             ╰╯",
	},
}

var foregrounds = []Template{
	{
		"█   █   █   █   █",
		" ░       ░       ",
		"█   █   █   █   █",
		"     ░       ░   ",
		"█   █   █   █   █",
		" ░       ░       ",
		"█   █   █   █   █",
		"     ░       ░   ",
		"█   █   █   █   █",
	},
	{
		"",
		"  █   █   █   █",
		"   █   █   █   █",
		"    █   █   █   █",
		"",
		"  █   █   █   █",
		"   █   █   █   █",
		"    █   █   █   █",
		"",
	},
	{
		"",
		"",
		"",
		"    █    █    █",
		"   █ █  █ █  █ █",
		"    █    █    █",
		"",
		"",
		"",
	},
	{
		"      █     █",
		"     █ █   █ █",
		"      █     █",
		"   █     █     █",
		"  █ █   █ █   █ █",
		"   █     █     █",
		"      █     █",
		"     █ █   █ █",
		"      █     █",
	},
	{
		"",
		"        ░▒░",
		"       ░▒░▒░",
		"      ░▒░▒░▒░",
		"     ░▒░▒░▒░▒░",
		"      ░▒░▒░▒░",
		"       ░▒░▒░",
		"        ░▒░",
		"",
	},
	{
		"      █     █",
		"     █┼█   █┼█",
		"      █     █",
		"   █     █     █",
		"  █┼█   █┼█   █┼█",
		"   █     █     █",
		"      █     █",
		"     █┼█   █┼█",
		"      █     █",
	},
	{
		"",
		"  ╳   ╳   ╳   ╳",
		"   ╳   ╳   ╳   ╳",
		"    ╳   ╳   ╳   ╳",
		"",
		"  ╳   ╳   ╳   ╳",
		"   ╳   ╳   ╳   ╳",
		"    ╳   ╳   ╳   ╳",
		"",
	},
	{
		"",
		"         ◓",
		"        ◐╬◑",
		"         ◒",
		"",
		"    ◓         ◓",
		"   ◐╬◑       ◐╬◑",
		"    ◒         ◒",
		"",
	},
	{
		"      ░█░█░█░",
		"     ░█░█░█░█░",
		"    ░█░█░█░█░█░",
		"   ░█░█░█░█░█░█░",
		"  ░█░█░█░█░█░█░█░",
		"   ░█░█░█░█░█░█░",
		"    ░█░█░█░█░█░",
		"     ░█░█░█░█░",
		"       █░█░█░",
	},
	{
		"       █░█░█",
		"      █░█░█░█",
		"     █░█░█░█░█",
		"    █░█░█░█░█░█",
		"   █░█░█░█░█░█░█",
		"    █░█░█░█░█░█",
		"     █░█░█░█░█",
		"      █░█░█░█",
		"       █░█░█",
	},
	{
		"         █",
		"       ░█░█░",
		"      ░█░█░█░",
		"     ░█░█░█░█░",
		"   █░█░█░█░█░█░█",
		"     ░█░█░█░█░",
		"      ░█░█░█░",
		"       ░█░█░",
		"         █",
	},
	{
		"    █ █     █ █",
		"     █       █",
		"    █ █     █ █",
		"        █ █",
		"         █",
		"        █ █",
		"    █ █     █ █",
		"     █       █",
		"    █ █     █ █",
	},
}
